import {
  Activity,
  AlignCenterVertical,
  Brain,
  CheckCircle,
  Droplet,
  Dumbbell,
  Eye,
  Flame,
  Flower2,
  Focus,
  Gamepad,
  Hand,
  Heart,
  HeartPulse,
  Leaf,
  Monitor,
  Moon,
  Notebook,
  Palmtree,
  Salad,
  Shield,
  Smile,
  Sparkles,
  StretchHorizontal,
  StretchVertical,
  Sun,
  Target,
  ToyBrick,
  UserCheck,
  Users,
  Wind,
  Zap,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  activity: Activity,
  "align-center-vertical": AlignCenterVertical,
  brain: Brain,
  "check-circle": CheckCircle,
  droplet: Droplet,
  dumbbell: Dumbbell,
  eye: Eye,
  flame: Flame,
  flower: Flower2,
  focus: Focus,
  gamepad: Gamepad,
  hand: Hand,
  heart: Heart,
  "heart-pulse": HeartPulse,
  leaf: Leaf,
  monitor: Monitor,
  moon: Moon,
  notebook: Notebook,
  palmtree: Palmtree,
  salad: Salad,
  shield: Shield,
  smile: Smile,
  sparkles: Sparkles,
  "stretch-horizontal": StretchHorizontal,
  "stretch-vertical": StretchVertical,
  sun: Sun,
  target: Target,
  "toy-brick": ToyBrick,
  "user-check": UserCheck,
  users: Users,
  wind: Wind,
  zap: Zap,
};

export function expectIcon(name: string): LucideIcon {
  return iconMap[name] ?? Flower2;
}
